name: Integrate

on:
  pull_request:
    branches: [master]
  push:
    branches: ['*']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v2
        with:
          node-version: 15.2

      - name: Install firefox
        run: sudo apt install firefox

      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
          tar -xvzf geckodriver*
          sudo mv geckodriver /usr/local/bin
          geckodriver --version

      - name: Install dependencies
        run: make install

      # - name: Functional tests
      #   run: |
      #     npm run start &
      #     make test-ft

      # Deploy to heroku
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: e-dang-web-games
          heroku_email: ${{ secrets.HEROKU_EMAIL }}